name: steamy-build

env:
  CORE_LOVE_PACKAGE_PATH: ./steamy.love
  CORE_LOVE_ARTIFACT_NAME: core_steamy_package
  LINUX_LOVE_ARTIFACT_NAME: Steamy_Linux_AppImage
  PRODUCT_NAME: steamy
  BUNDLE_ID: net.videah.steamy
  DESCRIPTION: "Videah's Steamy Remote LÖVE Launcher"
  OUTPUT_FOLDER: ./build

on:
  push:
    tags:
      - '*'

jobs:
  build-core:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Build core love package
        uses: love-actions/love-actions-core@v1
        with:
          build-list: ./assets/ ./libs/ ./conf.lua ./main.lua ./init.lua
          package-path: ${{ env.CORE_LOVE_PACKAGE_PATH }}
      - name: Upload core love package
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}
          path: ${{ env.CORE_LOVE_PACKAGE_PATH }}

  build-linux:
    runs-on: ubuntu-latest
    needs: [build-core]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      # Download core love package here
      - name: Download core love package
        uses: actions/download-artifact@v3
        with:
          name: ${{ env.CORE_LOVE_ARTIFACT_NAME }}
      - name: Build Linux packages
        id: build-packages
        uses: love-actions/love-actions-linux@v1
        with:
          app-name: ${{ env.PRODUCT_NAME }}
          bundle-id: ${{ env.BUNDLE_ID }}
          description: ${{ env.DESCRIPTION }}
          version-string: "1.0.1"
          icon-path: ./assets/icon.png
          love-package: ${{ env.CORE_LOVE_PACKAGE_PATH }}
          product-name: ${{ env.PRODUCT_NAME }}
          output-folder: ${{ env.OUTPUT_FOLDER }}
      - name: Upload AppImage artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.LINUX_LOVE_ARTIFACT_NAME }}
          path: ${{ env.OUTPUT_FOLDER }}/${{ env.PRODUCT_NAME }}.AppImage

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: [build-core, build-linux]
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ${{ env.OUTPUT_FOLDER }}
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: ${{ env.OUTPUT_FOLDER }}/*
